title: Jinbum Park
description: jinb.park7@gmail.com
author: "Jinbum Park"
theme: minima
base_url: /

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/blog.md

include:
    - _pages

exclude:
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - robots.txt
    - sitemap.xml

#analytics:
#  provider: "google"
#  google:
#    tracking_id: "UA-171489496-1"
#    anonymize_ip: false
