title: Jinbum Park
description: jinb.park7@gmail.com
author: "Jinbum Park"
theme: minima

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/blog.md
  - _pages/about.md

include:
    - _pages

exclude:
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

analytics:
  provider: "google"
  google:
    tracking_id: "UA-171489496-1"
    anonymize_ip: false
